Tweaking install scripts

diff --git a/installs/ardopgui b/installs/ardopgui
--- a/installs/ardopgui
+++ b/installs/ardopgui
@@ -11,26 +11,53 @@
 # http://mawcg.org
 ############################################################################################################################
 
-mkdir -p $HOME/ardop
-cd $HOME/ardop
-wget https://www.cantab.net/users/john.wiseman/Downloads/Beta/piARDOP_GUI || echo "Can't download piARDOP_GUI" >> $BUILDLOG
-sudo chmod +x $HOME/ardop/piARDOP_GUI
+echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
+echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
+echo "ARDOP GUI Installation Started at `date`" >> $1
+echo " " >> $1
+echo " " >> $1
+
+#####################################
+# Installing
+#####################################
+
+mkdir -p $3/ardop
+cd $3/ardop
+wget https://www.cantab.net/users/john.wiseman/Downloads/Beta/piARDOP_GUI || echo "*** ERROR ***  Can't download piARDOP_GUI" >> $1
+sudo chmod +x $3/ardop/piARDOP_GUI
+
+#####################################
+# Creating Desktop Icon
+#####################################
+
 cat > ardopgui.desktop <<EOF
 [Desktop Entry]
 Name=ARDOP GUI
 GenericName=ARDOP GUI
 Comment=Graphical User Interface for ARDOP modem
-Exec=$HOME/ardop/piARDOP_GUI
+Exec=$3/ardop/piARDOP_GUI
 Terminal=false
 Type=Application
 Categories=Network;HamRadio;
 EOF
 
 sudo mv ardopgui.desktop /usr/share/applications/
-FILE=$HOME/.config/G8BPQ/ARDOP_GUI.conf
-mkdir -p $HOME/.config/G8BPQ
+
+
+#####################################
+# Create Config File
+#####################################
+
+FILE=$3/.config/G8BPQ/ARDOP_GUI.conf
+mkdir -p $3/.config/G8BPQ
 touch $FILE
 echo "[General]" >> $FILE
-echo "Host=local" >> $FILE
 echo "Port=8515" >> $FILE
-echo "ARDOP-GUI installed" >> $BUILDLOG
+echo "Host=local" >> $FILE
+
+echo " " >> $1
+echo " " >> $1
+echo "ARDOP GUI install completed  at `date`" >> $1
+echo " " >> $1
+echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
+echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
diff --git a/installs/direwolf b/installs/direwolf
--- a/installs/direwolf
+++ b/installs/direwolf
@@ -11,13 +11,34 @@
 # http://mawcg.org
 ############################################################################################################################
 
-cd $HOME
-git clone https://www.github.com/wb2osz/direwolf || echo "Can't download DIREWOLF" >> $BUILDLOG
-cd $HOME/direwolf
+echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
+echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
+echo "DIREWOLF Installation Started at `date`" >> $1
+echo " " >> $1
+echo " " >> $1
+
+#####################################
+# Installing
+#####################################
+
+cd $3
+git clone https://www.github.com/wb2osz/direwolf || echo "Can't download DIREWOLF" >> $1
+cd $3/direwolf
 sudo apt-get install -y libasound2-dev
 make
 sudo make install
 make install-conf
-sed -i "s/N0CALL/$CALL/" "$HOME/direwolf.conf"
-sed -i 's/# ADEVICE  plughw:1,0/ADEVICE  plughw:1,0/' $HOME/direwolf.conf
-echo "DIREWOLF installed" >> $BUILDLOG
+
+#####################################
+# Modify Config File
+#####################################
+
+sed -i "s/N0CALL/$4/" "$HOME/direwolf.conf"
+sed -i 's/# ADEVICE  plughw:1,0/ADEVICE  plughw:1,0/' $3/direwolf.conf
+
+echo " " >> $1
+echo " " >> $1
+echo "DIREWOLF install completed  at `date`" >> $1
+echo " " >> $1
+echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
+echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
diff --git a/installs/hamlib b/installs/hamlib
--- a/installs/hamlib
+++ b/installs/hamlib
@@ -11,13 +11,29 @@
 # http://mawcg.org
 ############################################################################################################################
 
-cd $1
-wget https://sourceforge.net/projects/hamlib/files/hamlib/3.3/hamlib-3.3.tar.gz || echo "Can't download HAMLIB" >> $BUILDLOG
-tar -xzf $DIR/hamlib-3.3.tar.gz
-rm $DIR/hamlib-3.3.tar.gz
-cd $DIR/hamlib-3.3
+echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
+echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
+echo "HAMLIB Installation Started at `date`" >> $1
+echo " " >> $1
+echo " " >> $1
+
+#####################################
+# Installing
+#####################################
+
+cd $3
+wget https://sourceforge.net/projects/hamlib/files/hamlib/3.3/hamlib-3.3.tar.gz || echo "*** ERROR ***  Can't download HAMLIB" >> $1
+tar -xzf $3/hamlib-3.3.tar.gz
+rm $3/hamlib-3.3.tar.gz
+cd $3/hamlib-3.3
 ./configure
 make 
 sudo make install
 sudo ldconfig
-echo "HAMLIB installed" >> $BUILDLOG
+
+echo " " >> $1
+echo " " >> $1
+echo "HAMLIB install completed  at `date`" >> $1
+echo " " >> $1
+echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
+echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
diff --git a/installs/js8call b/installs/js8call
--- a/installs/js8call
+++ b/installs/js8call
@@ -11,12 +11,39 @@
 # http://mawcg.org
 ############################################################################################################################
 
-cd $DIR
+############################################################################################################################
+# direwolf
+#
+# Script to setup and install the direwolf virtual tnc
+#
+# Author: Mike Myers (K3DO)
+#
+# This is a project of the Mid Atlantic Wireless Communication Group
+# http://mawcg.org
+############################################################################################################################
+
+echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
+echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
+echo "JS8Call Installation Started at `date`" >> $1
+echo " " >> $1
+echo " " >> $1
+
+#####################################
+# Installing
+#####################################
+
+cd $2
 JS8LATE=$(curl -s http://files.js8call.com/latest.html | grep armhf | awk '{ print $2 }' | sed 's/href=//' | sed 's/"//g')
 JS8PKG=$(curl -s http://files.js8call.com/latest.html | grep armhf | awk '{ print $2 }' | sed 's/\///g' | sed 's/href="http:files.js8call.com[0-9].[0-9].[0-9]//' | sed 's/"//')
-wget $JS8LATE || echo "Can't Download JS8Call" >> $BUILDLOG
+wget $JS8LATE || echo "*** ERROR ***  Can't Download JS8Call" >> $1
 sudo dpkg -i $JS8PKG
 sudo apt-get --fix-broken -y install
 sudo dpkg -i $JS8PKG
-echo "JS8Call installed" >> $BUILDLOG
+
+echo " " >> $1
+echo " " >> $1
+echo "JS8Call install completed  at `date`" >> $1
+echo " " >> $1
+echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
+echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
 
diff --git a/installs/pat b/installs/pat
--- a/installs/pat
+++ b/installs/pat
@@ -11,25 +11,44 @@
 # http://mawcg.org
 ############################################################################################################################
 
-cd $1
-wget https://github.com/la5nta/pat/releases/download/v0.9.0/pat_0.9.0_linux_armhf.deb || echo "Can't download Pat Winlink" >> $BUILDLOG 
-	sudo dpkg -i $DIR/pat_0.9.0_linux_armhf.deb
-	pat http &
-	sudo killall pat
-	sudo systemctl start pat@$WHO
-	sudo systemctl enable pat@$WHO
-	#/usr/bin/pat http &
-	#sudo killall pat
-	cd $DIR
-	wget https://raw.githubusercontent.com/km4ack/patmenu/master/patlogin
-	bash patlogin
-	jq '.ax25.rig = '\"my-rig\"'' $HOME/.wl2k/config.json | jq '.ardop.rig = '\"my-rig\"'' | jq '.hamlib_rigs = {'\"my-rig\"': {"address": "127.0.0.1:4532", "network": "tcp"}}' > ~/Desktop/config.json
-	mv ~/Desktop/config.json ~/.wl2k/config.json
-	sed -i "s/\"http_addr\": \".*\",/\"http_addr\": \"0.0.0.0:8080\",/" $HOME/.wl2k/config.json
-		#enable gps in pat is gps=yes
-		if [ $GPS = "yes" ]
-		then
-		sed -i 's/"enable_http": false,/"enable_http": true,/' $HOME/.wl2k/config.json
-		fi
-		echo "Pat Winlink installed" >> $BUILDLOG
+echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
+echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
+echo "Pat Installation Started at `date`" >> $1
+echo " " >> $1
+echo " " >> $1
 
+#####################################
+# Installing
+#####################################
+
+cd $1
+wget https://github.com/la5nta/pat/releases/download/v0.9.0/pat_0.9.0_linux_armhf.deb || echo "*** ERROR ***  Can't download Pat Winlink" >> $1 
+sudo dpkg -i $DIR/pat_0.9.0_linux_armhf.deb
+pat http &
+sudo killall pat
+sudo systemctl start pat@$WHO
+sudo systemctl enable pat@$WHO
+
+cd $3
+wget https://raw.githubusercontent.com/km4ack/patmenu/master/patlogin
+bash patlogin
+jq '.ax25.rig = '\"my-rig\"'' $HOME/.wl2k/config.json | jq '.ardop.rig = '\"my-rig\"'' | jq '.hamlib_rigs = {'\"my-rig\"': {"address": "127.0.0.1:4532", "network": "tcp"}}' > ~/Desktop/config.json
+mv ~/Desktop/config.json ~/.wl2k/config.json
+sed -i "s/\"http_addr\": \".*\",/\"http_addr\": \"0.0.0.0:8080\",/" $HOME/.wl2k/config.json
+
+#####################################
+# Install GPS if selected
+#####################################
+
+#enable gps in pat is gps=yes
+if [ $GPS = "yes" ]
+then
+	sed -i 's/"enable_http": false,/"enable_http": true,/' $HOME/.wl2k/config.json
+fi
+
+echo " " >> $1
+echo " " >> $1
+echo "Pat install completed  at `date`" >> $1
+echo " " >> $1
+echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
+echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
diff --git a/installs/piardop b/installs/piardop
--- a/installs/piardop
+++ b/installs/piardop
@@ -11,9 +11,24 @@
 # http://mawcg.org
 ############################################################################################################################
 
+echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
+echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
+echo "PIARDOP Installation Started at `date`" >> $1
+echo " " >> $1
+echo " " >> $1
+
+#####################################
+# Installing
+#####################################
+
 mkdir -p $HOME/ardop
 cd $HOME/ardop
-wget https://www.cantab.net/users/john.wiseman/Downloads/Beta/piardopc || echo "Can't download PIARDOPC" >> $BUILDLOG
+wget https://www.cantab.net/users/john.wiseman/Downloads/Beta/piardopc || echo "*** ERROR ***  Can't download PIARDOPC" >> $1
 sudo chmod +x $HOME/ardop/piardopc
-echo "PIARDOPC installed" >> $BUILDLOG
 
+echo " " >> $1
+echo " " >> $1
+echo "PIARDOP install completed  at `date`" >> $1
+echo " " >> $1
+echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
+echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
diff --git a/installs/wsjtx b/installs/wsjtx
--- a/installs/wsjtx
+++ b/installs/wsjtx
@@ -11,10 +11,25 @@
 # http://mawcg.org
 ############################################################################################################################
 
-cd $DIR
-wget --no-check-certificate https://physics.princeton.edu/pulsar/k1jt/wsjtx_2.1.0_armhf.deb || echo "Can't download WSJTX" >> $BUILDLOG
+echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
+echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
+echo "WSJTX Installation Started at `date`" >> $1
+echo " " >> $1
+echo " " >> $1
+
+#####################################
+# Installing
+#####################################
+
+cd $3
+wget --no-check-certificate https://physics.princeton.edu/pulsar/k1jt/wsjtx_2.1.0_armhf.deb || echo "*** ERROR ***  Can't download WSJTX" >> $1
 sudo dpkg -i wsjtx_2.1.0_armhf.deb
 sudo apt-get --fix-broken -y install
 sudo dpkg -i wsjtx_2.1.0_armhf.deb
-echo "WSJTX installed" >> $BUILDLOG
 
+echo " " >> $1
+echo " " >> $1
+echo "WSJTX install completed  at `date`" >> $1
+echo " " >> $1
+echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
+echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
